# Generated by Django 5.0.2 on 2024-02-08 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicio_riego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_riego',
            name='id_cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_riego', to='api.tipo_cotizacion'),
        ),
        migrations.CreateModel(
            name='servicio_electrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('detalle_servicio', models.TextField(max_length=400)),
                ('valor_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cotizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_electrico', to='api.tipo_cotizacion')),
            ],
        ),
    ]
