# Generated by Django 5.0.2 on 2024-02-08 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='medida_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medida_producto', to='api.productos')),
            ],
        ),
    ]
