# Generated by Django 5.0.2 on 2024-02-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medida_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='iva',
            field=models.CharField(choices=[('0', '12'), ('1', '0')], default=False, max_length=6),
        ),
    ]
