# Generated by Django 5.0.2 on 2024-02-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productos_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_cotizacion_riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=144)),
            ],
        ),
        migrations.RenameModel(
            old_name='tipo_cotizacion',
            new_name='tipo_cotizacion_electrico',
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.tipo_cotizacion_riego'),
        ),
        migrations.AlterField(
            model_name='servicio_riego',
            name='id_cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_riego', to='api.tipo_cotizacion_riego'),
        ),
    ]
