# Generated by Django 5.0.2 on 2024-02-08 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tipo_cotizacion_riego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio_electrico',
            name='id_cotizacion',
        ),
        migrations.RemoveField(
            model_name='servicio_riego',
            name='id_cotizacion',
        ),
        migrations.AlterField(
            model_name='servicio_electrico',
            name='nombre_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_electrico', to='api.tipo_cotizacion_electrico'),
        ),
        migrations.AlterField(
            model_name='servicio_riego',
            name='nombre_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_riego', to='api.tipo_cotizacion_riego'),
        ),
    ]
