# Generated by Django 4.2.10 on 2024-02-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_servicio_electrico_id_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aspersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='conducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='goteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='riego_Arboles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='riego_invernadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='riego_jardines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='riego_tecnificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id_cotizacion',
        ),
        migrations.RemoveField(
            model_name='servicio_electrico',
            name='nombre_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio_riego',
            name='nombre_servicio',
        ),
        migrations.DeleteModel(
            name='medida_producto',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.DeleteModel(
            name='servicio_electrico',
        ),
        migrations.DeleteModel(
            name='servicio_riego',
        ),
        migrations.DeleteModel(
            name='tipo_cotizacion_electrico',
        ),
        migrations.DeleteModel(
            name='tipo_cotizacion_riego',
        ),
    ]
