# Generated by Django 4.2.10 on 2024-02-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aspersion_conducciones_goteo_riego_arboles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio_riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aspersion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_aspersion', to='api.aspersion')),
                ('id_conducciones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_conducciones', to='api.conducciones')),
                ('id_goteo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_goteo', to='api.goteo')),
                ('id_riego_Arboles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_riego_Arboles', to='api.riego_arboles')),
                ('id_riego_invernadero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_riego_invernadero', to='api.riego_invernadero')),
                ('id_riego_jardines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_riego_jardines', to='api.riego_jardines')),
                ('id_riego_tecnificados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicio_riego_tecnificados', to='api.riego_tecnificados')),
            ],
        ),
    ]
